import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react";
// import { Biconomy } from "@biconomy/mexa";
import { config } from "../constants";
import { ethers } from "ethers";
import { useProvider, useSigner, useContract, useAccount } from "wagmi";
import { ConnectButton } from "@rainbow-me/rainbowkit";

export default async function Home() {
  const [newMood, setNewMood] = useState("");
  const [currentMood, setCurrentMood] = useState("");

  const { address } = useAccount();
  const provider = useProvider();
  const { data: signer } = useSigner();
  const Moodcontract = useContract({
    addressOrName: config.contract.address,
    contractInterface: config.contract.abi,
    signerOrProvider: signer || provider,
  });

  useEffect(() => {
    GetMood();
  }, []);

  const GetMood = async () => {
    try {
      const mood = await Moodcontract.getMood();
      console.log(mood);
      setCurrentMood(mood);
    } catch (err) {
      console.log(err);
    }
  };

  const SetMood = async () => {
    try {
      const biconomy = new Biconomy(provider, {
        apiKey: config.apiKey.prod,
        contractAddresses: [config.contract.address],
      });
      const biconomyProvider = await biconomy.provider;
      const contractInstance = new ethers.Contract(
        config.contract.address,
        config.contract.abi,
        biconomy.ethersProvider
      );
      await biconomy.init();
      const { data } = await contractInstance.populateTransaction.setMood(
        newMood
      );
      let txParams = {
        data: data,
        to: config.contract.address,
        from: address,
        signatureType: "EIP712_SIGN",
      };
      await biconomyProvider.send("eth_sendTransaction", [txParams]);
    } catch (err) {
      console.log(err);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Biconomy Gasless transaction dApp</h1>

        <p className={styles.description}>
          Set and Get your Mood without paying any Gas on Polygon Mumbai Chain
        </p>
        <ConnectButton />
        <div>
          <div>
            <a>Current Mood : {currentMood} </a>
          </div>
          <div className={styles.firstrow}>
            <input
              className={styles.input}
              type="text"
              value={newMood}
              placeholder="Mood"
              onChange={(e) => setNewMood(e.target.value)}
            ></input>
          </div>
          <div className={styles.buttonRow}>
            <button onClick={SetMood} className={styles.button}>
              Lets Go 🚀
            </button>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://twitter.com/0xdhruva"
          target="_blank"
          rel="noopener noreferrer"
        >
          Built by @0xDhruva
        </a>
        <a href="https://github.com/Dhruv-2003">Github</a>
      </footer>
    </div>
  );
}
